/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneumann.node;

import nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TBooleanoVerdade extends Token
{
    public TBooleanoVerdade()
    {
        super.setText("verdade");
    }

    public TBooleanoVerdade(int line, int pos)
    {
        super.setText("verdade");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBooleanoVerdade(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBooleanoVerdade(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBooleanoVerdade text.");
    }
}
