/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneumann.node;

import nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TOperadorBooleanoNao extends Token
{
    public TOperadorBooleanoNao()
    {
        super.setText("nao");
    }

    public TOperadorBooleanoNao(int line, int pos)
    {
        super.setText("nao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperadorBooleanoNao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperadorBooleanoNao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperadorBooleanoNao text.");
    }
}
