/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneumann.node;

import nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TOperadorBooleanoOu extends Token
{
    public TOperadorBooleanoOu()
    {
        super.setText("ou");
    }

    public TOperadorBooleanoOu(int line, int pos)
    {
        super.setText("ou");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperadorBooleanoOu(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperadorBooleanoOu(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperadorBooleanoOu text.");
    }
}
