/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneumann.node;

import nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TReservadaNumerico extends Token
{
    public TReservadaNumerico()
    {
        super.setText("numerico");
    }

    public TReservadaNumerico(int line, int pos)
    {
        super.setText("numerico");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReservadaNumerico(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReservadaNumerico(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReservadaNumerico text.");
    }
}
